CREATE TABLE "APP"."CDH_VERSION" ("VER_ID" BIGINT NOT NULL, "SCHEMA_VERSION" VARCHAR(127) NOT NULL, "VERSION_COMMENT" VARCHAR(255));
ALTER TABLE "APP"."CDH_VERSION" ADD CONSTRAINT "CDH_VERSION_PK" PRIMARY KEY ("VER_ID");

INSERT INTO "APP"."CDH_VERSION" (VER_ID, SCHEMA_VERSION, VERSION_COMMENT)
SELECT "VER_ID", "SCHEMA_VERSION_V2", "VERSION_COMMENT"
FROM "APP"."VERSION" WHERE "VER_ID"=1;

ALTER TABLE "APP".VERSION DROP COLUMN SCHEMA_VERSION_V2;
