CREATE TABLE IF NOT EXISTS `CDH_VERSION` (
  `VER_ID` BIGINT NOT NULL,
  `SCHEMA_VERSION` VARCHAR(127) NOT NULL,
  `VERSION_COMMENT` VARCHAR(255),
  PRIMARY KEY (`VER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO CDH_VERSION (VER_ID, SCHEMA_VERSION, VERSION_COMMENT)
SELECT VER_ID, SCHEMA_VERSION_V2, VERSION_COMMENT
FROM VERSION WHERE VER_ID=1;

ALTER TABLE VERSION DROP COLUMN SCHEMA_VERSION_V2;
