--
-- Table structure for CDH_VERSION
--
CREATE TABLE "CDH_VERSION" (
  "VER_ID" bigint,
  "SCHEMA_VERSION" character varying(127) NOT NULL,
  "VERSION_COMMENT" character varying(255) NOT NULL
);

ALTER TABLE ONLY "CDH_VERSION" ADD CONSTRAINT "CDH_VERSION_pkey" PRIMARY KEY ("VER_ID");

INSERT INTO "CDH_VERSION" ("VER_ID", "SCHEMA_VERSION", "VERSION_COMMENT")
SELECT "VER_ID", "SCHEMA_VERSION_V2", "VERSION_COMMENT"
FROM "VERSION" WHERE "VER_ID"=1;

ALTER TABLE "VERSION" DROP COLUMN "SCHEMA_VERSION_V2";
